#将服务注册到注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      #healthcheck:
      #enabled: true  #开启自定义健康检查
  instance:
    #eureka服务器在接收到最后一个心跳之后等待的时间，然后才能从列表中删除此实例 默认90s（开发环境)
    lease-expiration-duration-in-seconds: 10
    #eureka客户端需要向eureka服务器发送心跳的频率 默认30s （开发环境)
    lease-renewal-interval-in-seconds: 1
    # ip地址
    #ip-address: 固定ip地址
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #preferIpAddress: true
#配置服务名称及端口
server:
  port: 9001
spring:
  application:
    name: springcloud-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gfo_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    default-property-inclusion=non_null:
mybatis:
  mapper-locations: classpath*:mappers/*.xml

kd:
  appion:
    name: 生产者：

